# SPDX-License-Identifier: MIT
#
# DATA takes the rest of the disk at first boot; x-systemd.growfs in /etc/fstab grows the
# filesystem when /data is mounted.

[Partition]
Type=linux-generic
Label=data
